apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: aylee-front
  labels:
    app.kubernetes.io/name: aylee-front
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - aylee-demo.apps.ldcc-cluster.gavd.p1.openshiftapps.com
