apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: aylee-front
  labels:
    app.kubernetes.io/name: aylee-front
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: aylee-front
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
